[General]
# Если нужно фильтровать трафик (по умолчанию выключено)
# ReportStats = false
# MAVLink-маршрутизатор может вести логи (tlog), если нужно
# Log = /var/log/mavlink-router

# 1. Забираем данные с полетника (--master)
[UartEndpoint fcu]
Device = /dev/ttyACM0
Baud = 2000000

# 2. Отдаем на MAVROS (--out=udpout:127.0.0.1:14555)
[UdpEndpoint mavros]
Mode = normal
Address = 127.0.0.1
Port = 14555

# 3. Отдаем на твой Go-скрипт (--out=udpout:127.0.0.1:14550)
[UdpEndpoint orin_shutdown]
Mode = normal
Address = 127.0.0.1
Port = 14550

# 4. Раздаем по TCP для Mission Planner (--out=tcpin:0.0.0.0:5760)
[TcpServer mission_planner]
Address = 0.0.0.0
Port = 5760

[Log]
LogDir = /home/andriy/mavlogs