# === ЭТАП 1: СБОРКА (Тяжелый образ со всеми инструментами) ===
FROM nvcr.io/nvidia/isaac/ros:aarch64-ros2_humble_4c0c55dddd2bbcc3e8d5f9753bee634c AS builder

# Настраиваем окружение для CUDA
ENV PATH=/usr/local/cuda/bin:$PATH
ENV LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH

WORKDIR /workspace
COPY ./src ./src

# Компилируем софт
RUN colcon build --symlink-install \
    --cmake-args -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda -DBUILD_TESTING=OFF

# === ЭТАП 2: ПРОДАКШН (Чистый образ без исходников) ===
FROM nvcr.io/nvidia/isaac/ros:aarch64-ros2_humble_4c0c55dddd2bbcc3e8d5f9753bee634c

WORKDIR /workspace

# Копируем ИЗ ЭТАПА СБОРКИ только готовую папку install
COPY --from=builder /workspace/install ./install

# Настраиваем автозапуск (DDS и source) в bashrc контейнера
RUN echo "source /workspace/install/setup.bash" >> ~/.bashrc && \
    echo "export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp" >> ~/.bashrc

# Команда по умолчанию при старте контейнера на дроне
CMD ["ros2", "launch", "install/share/gxf_isaac_camera_utils/launch/camera_split.launch.py"]